#!/usr/bin/env python3
"""
Serve the `web/` directory over HTTPS for local development.

Spotify now requires secure redirect URIs, so run this server with the
development certificates generated by `scripts/generate_dev_certs.sh`.
"""

import argparse
import functools
import http.server
import pathlib
import ssl


def create_server(port, directory, cert_path, key_path):
    handler = functools.partial(
        http.server.SimpleHTTPRequestHandler,
        directory=str(directory),
    )

    httpd = http.server.HTTPServer(("0.0.0.0", port), handler)
    httpd.socket = ssl.wrap_socket(
        httpd.socket,
        server_side=True,
        certfile=str(cert_path),
        keyfile=str(key_path),
    )
    return httpd


def main():
    parser = argparse.ArgumentParser(
        description="Serve the web UI over HTTPS for local development."
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port to serve on (default: 8000)",
    )
    parser.add_argument(
        "--cert",
        type=pathlib.Path,
        default=pathlib.Path(__file__).parent.parent / "certs" / "dev.crt",
        help="Path to the TLS certificate (default: certs/dev.crt)",
    )
    parser.add_argument(
        "--key",
        type=pathlib.Path,
        default=pathlib.Path(__file__).parent.parent / "certs" / "dev.key",
        help="Path to the TLS private key (default: certs/dev.key)",
    )
    args = parser.parse_args()

    if not args.cert.exists() or not args.key.exists():
        raise SystemExit(
            "TLS assets not found. Run scripts/generate_dev_certs.sh first."
        )

    server = create_server(args.port, pathlib.Path(__file__).parent, args.cert, args.key)
    print(f"Serving HTTPS on https://localhost:{args.port}")
    print("Press Ctrl+C to stop.")
    server.serve_forever()


if __name__ == "__main__":
    main()
